<a href="https://colab.research.google.com/github/2303A51664/AIML1/blob/main/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Implementing Lists using Numpy
import numpy as np
lst = [1,2,3,4,5,6]
arr = np.array(lst)
print(arr)



[1 2 3 4 5 6]


In [1]:
#Implementing Arrays using Numpy
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#Identifying type usinf "type()" method
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
#Performing mathematical operations
#1.Multiplication
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
mul = np.multiply(a, b)
print(mul)
#2.division
div = np.divide(a, b)
print(div)
#3.Poweroff
power = np.power(a, b)
print(power)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [5]:
#Performing mathematical operations
#1.Multiplication
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
mul = np.multiply(a, b)
print(mul)
#2.division
div = np.divide(a, b)
print(div)
#3.Poweroff
power = np.power(a, b)
print(power)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [8]:
#Performing mathematical operations
#1.Multiplication
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
mul = np.multiply(a, b)
print(mul)
#2.division
div = np.divide(a, b)
print(div)
#3.Poweroff
power = np.power(a, b)
print(power)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [9]:
#Implement Lists using Pandas
import pandas as pd
lst = [1,2,3,4]
arr = pd.Series(lst)
print(arr)

0    1
1    2
2    3
3    4
dtype: int64
