<a href="https://colab.research.google.com/github/2303A51664/AIML1/blob/main/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Implementing Lists using Numpy
import numpy as np
lst = [1,2,3,4,5,6]
arr = np.array(lst)
print(arr)



[1 2 3 4 5 6]


In [1]:
#Implementing Arrays using Numpy
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#Identifying type usinf "type()" method
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
#Performing mathematical operations
#1.Multiplication
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
mul = np.multiply(a, b)
print(mul)
#2.division
div = np.divide(a, b)
print(div)
#3.Poweroff
power = np.power(a, b)
print(power)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [5]:
#Performing mathematical operations
#1.Multiplication
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
mul = np.multiply(a, b)
print(mul)
#2.division
div = np.divide(a, b)
print(div)
#3.Poweroff
power = np.power(a, b)
print(power)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [8]:
#Performing mathematical operations
#1.Multiplication
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
mul = np.multiply(a, b)
print(mul)
#2.division
div = np.divide(a, b)
print(div)
#3.Poweroff
power = np.power(a, b)
print(power)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [9]:
#Implement Lists using Pandas
import pandas as pd
lst = [1,2,3,4]
arr = pd.Series(lst)
print(arr)

0    1
1    2
2    3
3    4
dtype: int64


In [10]:
#Implement arrays using pandas
import pandas as pd
arr = [1,2,3,4,5]
arrays = pd.array(arr)
print(arrays)


<IntegerArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: Int64


In [11]:
#Identify thier type()
import pandas as pd
arr = [1,2,3,4,5]
arr1 = [0.1, 2.3, 4.6]
series = pd.Series(arr)#list in pandas does not have a datatype.
series1 = pd.Series(arr1)#Hence must be converted to Series.
data_type = series.dtype
data_type1 = series1.dtype
print(data_type)
print(data_type1)

int64
float64


In [12]:
#Combining texts
import pandas as pd
text1 = pd.Series(["Addition of Two: "])
text2 = pd.Series(["array1 + array2"])
print(text1.str.cat(text2))


0    Addition of Two: array1 + array2
dtype: object


In [15]:
#implement sin(), log(), log2(), exp() using pandas
import pandas as pd
import numpy as np #pandas does not have trignometric functions inbuilt
a = pd.Series([1,2,3])
sin = np.sin(a)
print(sin)
log = np.log(a)
print(log)
log2 = np.log2(a)
print(log2)
exp = np.exp(a)
print(exp)

0    0.841471
1    0.909297
2    0.141120
dtype: float64
0    0.000000
1    0.693147
2    1.098612
dtype: float64
0    0.000000
1    1.000000
2    1.584963
dtype: float64
0     2.718282
1     7.389056
2    20.085537
dtype: float64


In [16]:
#1. Generate a Data set for Health Care
import matplotlib.pyplot as plt
people = ["kiran", "arun", "vijay", "varun"]
age = [25, 30, 35, 40]
height = [145, 151, 165, 173]
weight = [45, 55, 65, 75]